### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by kevinsimper** [chandu87/hyf-javascript1#1]
Hi Chandrashekar

Thanks for making the homework 👍 I really like the page that you made that contains both sections neatly, they could have had a better headline, but it was easy to see after you clicked them!

You solved the homework really well!

You however made a mistake right here, as you capitalized the variable and the above it not. https://github.com/chandu87/hyf-javascript1/blob/master/week1/step1.js#L28

You coding style is also not consistent, you should be using spaces inbetween like here https://github.com/chandu87/hyf-javascript1/blob/master/week1/step1.js#L25 which you don't do here https://github.com/chandu87/hyf-javascript1/blob/master/week1/step1.js#L43 and other places.

You can for example see this coding style that airbnb has https://github.com/airbnb/javascript, or use a automatic formatter like prettier https://prettier.io/playground/

**Comment by chandu87** [comment]
Thank you for valuable comments. I just changed my mistakes and changed coding style and spaces.
Happy easter
